// Components
import Head from "next/head";
import type { NextPage } from "next";
import { Grid } from "@mui/material";
import AccountInputs from "../components/form/AccountInputs";
import PersonalInputs from "../components/form/PersonalInputs";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>

      <Grid container bgcolor="#e4e4e4" justifyContent="space-between">
        <Grid item>
          <AccountInputs />
        </Grid>
        <Grid item>
          <PersonalInputs />
        </Grid>
      </Grid>
    </div>
  );
};

export default Home;
